spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:mysql://localhost/db_fornecedor
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
            
            
